# Generated by Django 5.0.9 on 2024-11-04 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0191_module_bay_rebuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInventoryBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module_binding', to='dcim.inventoryitem')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_binding', to='dcim.module')),
            ],
            options={
                'verbose_name': 'Module Inventory Binding',
                'verbose_name_plural': 'Module Inventory Bindings',
            },
        ),
    ]
